"""Initial migration

Revision ID: 0c60f3d8b245
Revises: 950aa59ab63b
Create Date: 2025-02-16 15:51:34.371505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c60f3d8b245'
down_revision: Union[str, None] = '950aa59ab63b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('description', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'price')
    op.drop_column('orders', 'description')
    # ### end Alembic commands ###
