services:
  web:
    # Берем Dockerfile из каталога app
    build:
      context: .
      dockerfile: app/Dockerfile
    # Запускаем тестовый сервер
#    command: uvicorn main:app --host 0.0.0.0
    # Открываем порт 8000 внутри и снаружи
    ports:
      - 8000:8000
    # Ожидает запуск бд и кролика
    depends_on:
      - db
      - rabbitmq

  worker:
    image: worker
    build:
      context: .
      dockerfile: app/Dockerfile
    # Запускаем тестовый сервер
    command: python worker.py
#    # Открываем порт 8000 внутри и снаружи
#    ports:
#      - 8000:8000
    # Ожидает запуск бд и кролика
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=lupa
      - POSTGRES_PASSWORD=pupa2525
      - POSTGRES_DB=testtaskorders

  rabbitmq:
    image: rabbitmq:4.0.6-management
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=testuser
      - RABBITMQ_DEFAULT_PASS=testpass
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648

volumes:
  postgres_data:
  rabbitmq-data:
